on:
  push:
    branches:
      - master






jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "loge in to docker"
        run: docker login --username maanar --password dckr_pat_5swR5e9_TZQ0NMcOy1Qc7hO0dII